### ISSUE TITLE
Sidebar for Acc. details

### ISSUE THREAD

**Issue by toger5** [toger5/godotdevs-Forum#1]
I'am thinking about creating a sidebar for things like account details, new messages...
because the current location wont be usable when the featuredProject bar is implemented?
do you think this is a good idea or are there other ideas for placing your account details and news

**Comment by toger5** [comment]
okay I got it done now.
There is not much content in the sidebar but it shows the avatar and news of the current logged in member.
You also can tab and untab it with an nice animation.
untabbed:
![sidebaruntabbed](https://cloud.githubusercontent.com/assets/16718859/13542752/55a6d09a-e265-11e5-9e98-92958c856f31.PNG)
tabbed:
![sidebar tabbed](https://cloud.githubusercontent.com/assets/16718859/13542753/55a90d9c-e265-11e5-9948-a72b0c2fdbf2.PNG)

**Comment by KioriSun** [comment]
This looks good so far.
